name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./cmd/main.go

    - name: vet
      run: go vet ./...

    - name: gofmt
      uses: Jerome1337/gofmt-action@v1.0.4
      with:
        gofmt-path: './...'
        gofmt-flags: '-l -d'

    - name: golint
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './...'

