name: generate-markdown

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch
jobs:
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.4
          with:
            output_file_paths: '[./README.md, ./docs/*.md]'
