name: Tags

on: 
  push:
    tags:
      - '*'
      
jobs:      
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
            
      - run: mkdir -p dist
      - name: Build
        run: go build -o./dist/ -v .
      
      
      - uses: actions/upload-artifact@v2
        with:
            name: my-artifact
            path: dist/
