name: Tags

on: 
  push:
    branches:
      - '!*'
    tags:
      - 'v*'
      
jobs:      
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/..."
          binary_name: "tbb"
          ldflags: "-s -w"
          extra_files: LICENSE Readme.md
 
