on: workflow_dispatch
-
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Execute the scripts
        run: |
          cd docs/
          sudo apt install -y make nginx fcgiwrap gnutls-bin
          env FOLDERNAME=devca1 ./test1.sh
          env FOLDERNAME=devca1  ./test2.sh
           ./test3.sh
          cd ../cmd/first
          go run main.go
        shell: bash 
